version: '3.1'

services:

  postgres:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    ports:
      - 5432:5432

  web:
    image: nginx:stable-alpine3.19-perl
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    environment:
      - NGINX_HOST=flounder-alive-daily.ngrok-free.app
      - NGINX_PORT=80
    extra_hosts:
      - newhost:192.168.1.9